"""This is just a filler description."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/Mendee_note.ipynb.

# %% auto 0
__all__ = ['say_hello', 'foo']

# %% ../nbs/Mendee_note.ipynb 2
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'

# %% ../nbs/Mendee_note.ipynb 10
def foo(): pass
